#!/bin/bash
# fill_species.sh - Populate species information in HGT results
# This script takes the preliminary HGT table (with placeholder species columns)
# and fills in the actual recipient and donor species using lookup tables
# generated by merge_names.sh (which in turn used add_species.sh output).

INPUT_XLSX="FMT_list.xlsx"
if [ ! -f "$INPUT_XLSX" ]; then
    echo "Error: Input file $INPUT_XLSX does not exist!"
    exit 1
fi

# Use a Python one-liner to read the Excel file and write sample names to temp files
# Extract sample lists from Excel file
python3 - <<END
import pandas as pd
df = pd.read_excel("$INPUT_XLSX", engine='openpyxl')
pre_list = df['Pre-FMT'].dropna().astype(str).tolist()
donor_list = df['Donor'].dropna().astype(str).tolist()
post_list = df['Post-FMT'].dropna().astype(str).tolist()
with open('temp_pre.txt', 'w') as f: f.write('\n'.join(pre_list))
with open('temp_donor.txt', 'w') as f: f.write('\n'.join(donor_list))
with open('temp_post.txt', 'w') as f: f.write('\n'.join(post_list))
END

pre_samples=($(cat temp_pre.txt))
donor_samples=($(cat temp_donor.txt))
post_samples=($(cat temp_post.txt))
rm -f temp_*.txt

if [ ${#pre_samples[@]} -ne ${#donor_samples[@]} ] || [ ${#pre_samples[@]} -ne ${#post_samples[@]} ]; then
    echo "Error: Sample count mismatch!"
    exit 1
fi

mkdir -p final

for i in "${!pre_samples[@]}"; do
    post="${post_samples[i]}"
    donor="${donor_samples[i]}"

    echo "Processing sample: $post (Donor: $donor)"

    input_file="final/${post}_HGT_full.txt"                     # HGT table with placeholder species columns (10 & 11)
    output_file="final/${post}_HGT_statistics.txt"              # Final table with species filled
    recipient_map="result/${post}_name.txt"                     # Two‑column: recipient contig base name <tab> species
    donor_map="result/${donor}_name.txt"                        # Two‑column: donor contig base name <tab> species

    if [ ! -f "$input_file" ]; then
        echo "Warning: Input file $input_file not found, skipping"
        continue
    fi
    if [ ! -f "$recipient_map" ]; then
        echo "Warning: Recipient mapping file $recipient_map not found, skipping"
        continue
    fi
    if [ ! -f "$donor_map" ]; then
        echo "Warning: Donor mapping file $donor_map not found, skipping"
        continue
    fi

    # Use awk to merge species information into the HGT table
    awk -F'\t' -v OFS='\t' '
    BEGIN {
        # Use awk to merge species information into the HGT table
        while ((getline < "'$recipient_map'") > 0) {
            split($0, a, "\t");
            rec[a[1]] = a[2];
        }
        close("'$recipient_map'");
        # Load donor mapping: contig_base -> species
        while ((getline < "'$donor_map'") > 0) {
            split($0, a, "\t");
            don[a[1]] = a[2];
        }
        close("'$donor_map'");
    }
    {
        if (NR == 1) {
            # Header line: output as is (species columns are already there as placeholders)
            print;
        } else {
            # Extract the full recipient contig (column 6) and donor contig (column 7)
            rec_full = $6;
            don_full = $7;
            # Strip coordinates and gene number to get the base contig name
            # Recipient format: contig_start-end_geneNum -> remove _start-end_geneNum
            gsub(/_[0-9]*-[0-9]*_[0-9]*$/, "", rec_full);
            # Donor format: contig_start-end -> remove _start-end
            gsub(/_[0-9]*-[0-9]*$/, "", don_full);
            # Look up species from the loaded maps; default to empty string if not found
            rec_species = (rec_full in rec) ? rec[rec_full] : "";
            don_species = (don_full in don) ? don[don_full] : "";
            # Update columns 10 (recipient_species) and 11 (donor_species)
            $10 = rec_species;
            $11 = don_species;
            print;
        }
    }' "$input_file" > "$output_file"

    echo "Generated $output_file"
done

echo "All samples processed successfully!"
