#!/bin/bash
# merge_names.sh: Merge contig names with their assigned species names
# This script combines the list of unique contig names (from HGT_full.txt)
# with the species mapping files generated by add_species.sh.
# Output: two-column tab-separated files: contig_name <tab> species_name

# Input Excel file containing sample triples (Pre-FMT, Donor, Post-FMT)
INPUT_XLSX="FMT_list.xlsx"
if [ ! -f "$INPUT_XLSX" ]; then
    echo "Error: Input file $INPUT_XLSX does not exist!"
    exit 1
fi

# Extract sample lists from Excel file
python3 - <<END
import pandas as pd
df = pd.read_excel("$INPUT_XLSX", engine='openpyxl')
pre_list = df['Pre-FMT'].dropna().astype(str).tolist()
donor_list = df['Donor'].dropna().astype(str).tolist()
post_list = df['Post-FMT'].dropna().astype(str).tolist()
with open('temp_pre.txt', 'w') as f: f.write('\n'.join(pre_list))
with open('temp_donor.txt', 'w') as f: f.write('\n'.join(donor_list))
with open('temp_post.txt', 'w') as f: f.write('\n'.join(post_list))
END

pre_samples=($(cat temp_pre.txt))
donor_samples=($(cat temp_donor.txt))
post_samples=($(cat temp_post.txt))
rm -f temp_*.txt

if [ ${#pre_samples[@]} -ne ${#donor_samples[@]} ] || [ ${#pre_samples[@]} -ne ${#post_samples[@]} ]; then
    echo "Error: Input file $INPUT_XLSX does not exist!"
    exit 1
fi
# Main loop: process each sample pair (Post-FMT and Donor)
for i in "${!pre_samples[@]}"; do
    post="${post_samples[i]}"
    donor="${donor_samples[i]}"
    echo "Processing sample: $post (Donor: $donor)"

    # Define input and output file paths
    donor_names="result/${donor}_donor_names.txt"
    donor_species_map="result/${donor}_donor.species.map"
    donor_out="result/${donor}_name.txt"

    post_names="result/${post}_recipient_names.txt"
    post_species_map="result/${post}_recipient.species.map"
    post_out="result/${post}_name.txt"

     # Merge donor files if both exist
    if [ -f "$donor_names" ] && [ -f "$donor_species_map" ]; then
        paste "$donor_names" "$donor_species_map" | awk -F'\t' '{print $1"\t"$3}' > "$donor_out"
        echo "Generated $donor_out"
    else
        echo "Warning: donor files missing, skipping"
    fi

    # Merge recipient (post) files if both exist
    if [ -f "$post_names" ] && [ -f "$post_species_map" ]; then
        paste "$post_names" "$post_species_map" | awk -F'\t' '{print $1"\t"$3}' > "$post_out"
        echo "Generated $post_out"
    else
        echo "Warning: recipient files missing, skipping"
    fi
done

echo "All samples processed successfully!"
